default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['PGUSER'] %>
  password: <%= ENV['PGPASSWORD'] %>
  host: <%= ENV['PGHOST'] %>
  port: 5432

development:
  <<: *default
  database: proxima_development

test:
  <<: *default
  database: proxima_test

production:
  <<: *default
  database: proxima_production
